### ISSUE TITLE
Missing Docker Image

### ISSUE THREAD

**Issue by HoHunning** [antojoseph/fc#3]
Hello, I'm a student trying to run ClusterFuzz in a parallel way. I recently run your project, but it seems missing Docker Image: antojoseph/libfuzzer. 
How can I get it or I should create my owns? Do you have any suggestion?
Thanks for your time.

**Comment by antojoseph** [comment]
Hey,
You can get it from https://hub.docker.com/r/antojoseph/libfuzzer
